name: devicecounter
description: devicecounter
version: 0.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  flutter_native_splash: ^1.2.4

  xml: ^5.3.1
  collection: ^1.15.0-nullsafety.4
  uuid: ^3.0.5
  shell: ^2.0.0
  skein_upnp: ^1.0.0
  test: ^1.5.1
  lan_scanner: ^3.1.1
  network_info_plus: ^2.1.2
  url_launcher: ^6.0.18
  multicast_dns: ^0.3.1
  badges: ^2.0.2


flutter:
  uses-material-design: true

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "000000"
  image: "lib/assets/splash.png"